### ISSUE TITLE
using sys.argv in base.py?

### ISSUE THREAD

**Issue by guettli** [chrisglass/django_polymorphic#154]
We try to run django.setup() in our sitecustomize file.

This results in the following traceback.

Is sys.argv needed? Looks strange to my eyes.

```
Traceback (most recent call last):
  File "/home/foo_sho_d/lib/python2.7/site.py", line 703, in <module>
    main()
  File "/home/foo_sho_d/lib/python2.7/site.py", line 694, in main
    execsitecustomize()
  File "/home/foo_sho_d/lib/python2.7/site.py", line 548, in execsitecustomize
    import sitecustomize
  File "/home/foo_sho_d/src/foo-sho/sitecustomize.py", line 2, in <module>
    foo_sitecustomize.customize_site()
  File "/home/foo_sho_d/src/foo/foo/foo_sitecustomize.py", line 10, in customize_site
    django.setup()
  File "/home/foo_sho_d/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/foo_sho_d/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/foo_sho_d/local/lib/python2.7/site-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/foo_sho_d/local/lib/python2.7/site-packages/polymorphic/__init__.py", line 11, in <module>
    from .polymorphic_model import PolymorphicModel
  File "/home/foo_sho_d/local/lib/python2.7/site-packages/polymorphic/polymorphic_model.py", line 22, in <module>
    from .base import PolymorphicModelBase
  File "/home/foo_sho_d/local/lib/python2.7/site-packages/polymorphic/base.py", line 31, in <module>
    class PolymorphicModelBase(ModelBase):
  File "/home/foo_sho_d/local/lib/python2.7/site-packages/polymorphic/base.py", line 237, in PolymorphicModelBase
    if len(sys.argv) > 1:
AttributeError: 'module' object has no attribute 'argv'
```

**Comment by vdboor** [comment]
Yes, this check is needed. Please see the code and comments next to it:

https://github.com/chrisglass/django_polymorphic/blob/master/polymorphic/base.py#L228

**Comment by guettli** [comment]
What happens if you serialize within your own code? AFAIK the manage.py command dumpdata just uses the django serialization. If I call django serialization from my code, .... is this safe?

**Comment by vdboor** [comment]
In your own code, you can call `.non_polymorphic()` to serialize the base class, and then amend that with the regular model by serializing the polymorpic model.

The problem is that `dumpdata` will just serialize `Model.objects.all()`, which in the case of django-polymorphic, returns the child model instead of the original base class.

**Comment by guettli** [comment]
@vdboor thank you for the explanation.
