### ISSUE TITLE
Using Primary Key in Polymorphic Models

### ISSUE THREAD

**Issue by mjnaderi** [chrisglass/django_polymorphic#173]
I have two models:

```py
class A(PolymorphicModel):
    pass

class B(A):
    t = models.IntegerField(primary_key=True)
```

I have two instances of A and B in my database:

```
     b                                  a
------------                       -----------
a_ptr_id = 7       --------->      id = 7
t  (PK)  = 9
```

When I try to delete b:

    B.objects.get(pk=9).delete()

the delete command raises following exception:

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/abc/test/.venv/lib/python2.7/site-packages/django/db/models/base.py", line 895, in delete
    collector.collect([self])
  File "/home/abc/test/.venv/lib/python2.7/site-packages/django/db/models/deletion.py", line 212, in collect
    parent_objs = [getattr(obj, ptr.name) for obj in new_objs]
  File "/home/abc/test/.venv/lib/python2.7/site-packages/polymorphic/polymorphic_model.py", line 172, in accessor_function
    attr = model.base_objects.get(pk=self.pk)
  File "/home/abc/test/.venv/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/abc/test/.venv/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: A matching query does not exist.
```

I found out that it is trying to delete the A object with id=9, instead of id=7. It uses `b.pk` to find id of related A object. But the primary key in B, is not a_ptr_id, I have used my own PK.

I think it is good to add a note in documentation that says it is wrong to use a field as primary key in child models. Because the library creates and uses `*_ptr_id` as primary key.

Or maybe it can be solved in another way.

It can cause serious problems (In this example, it can delete the wrong A object, if A with id=9 exists)

For now, I changed `primary_key=True` to `unique=True` in my code.

Thanks.

**Comment by vdboor** [comment]
This is not a polymorphic issue, but a general Django model issue. Your subclasses models already have a primary key (the `*_ptr_id`) that Django needs for the subclassing. You can refer to it via the `.pk` field.

I can hardly imagine you want to introduce another PK on the model, so setting `unique=True` seems like a better solution.
