### ISSUE TITLE
ImportError: cannot import name 'PolymorphicModel'

### ISSUE THREAD

**Issue by mkane848** [chrisglass/django_polymorphic#189]
With the upgrade to v0.8, I began getting this error while using polumorphic in conjunction with django-filer. Reverting back to v0.7.2 fixed the issue, but here's the error output. I'm on Windows 10 using Python 3.5

```
(env) U:\project\intranet>python manage.py runserver
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x0000003437941BF8>
Traceback (most recent call last):
  File "U:\project\env\lib\site-packages\django\utils\autoreload.py", line 229, in wrapper
    fn(*args, **kwargs)
  File "U:\project\env\lib\site-packages\django\core\management\commands\runserver.py", line 107, in inner_run
    autoreload.raise_last_exception()
  File "U:\project\env\lib\site-packages\django\utils\autoreload.py", line 252, in raise_last_exception
    six.reraise(*_exception)
  File "U:\project\env\lib\site-packages\django\utils\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "U:\project\env\lib\site-packages\django\utils\autoreload.py", line 229, in wrapper
    fn(*args, **kwargs)
  File "U:\project\env\lib\site-packages\django\__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "U:\project\env\lib\site-packages\django\apps\registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "U:\project\env\lib\site-packages\django\apps\config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "U:\project\env\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "U:\project\env\lib\site-packages\filer\models\__init__.py", line 3, in <module>
    from filer.models.clipboardmodels import *  # flake8: noqa
  File "U:\project\env\lib\site-packages\filer\models\clipboardmodels.py", line 9, in <module>
    from filer.models import filemodels
  File "U:\project\env\lib\site-packages\filer\models\filemodels.py", line 14, in <module>
    from polymorphic import PolymorphicModel, PolymorphicManager
ImportError: cannot import name 'PolymorphicModel'
```

**Comment by aramboi** [comment]
Getting this also under Ubuntu 15.10 with latest Python 3.5.0+

**Comment by robertavram** [comment]
Confirming this issue as well. Core Models should not be removed since it can introduce breaking changes. This update should have been labeled 1.*.* since it has core restructuring.

**Comment by robertavram** [comment]
If you update django-filer to 1.0.5 the requirement is fixed to request polymorphic 0.7<

**Comment by tng10** [comment]
For versions (> 0.8) you must use <b>from polymorphic.models import PolymorphicModel</b>

**Comment by vdboor** [comment]
You'll have to update some imports. there are a few backwards incompatible changes in 0.8:
http://django-polymorphic.readthedocs.org/en/latest/changelog.html#version-0-8-2015-12-28
