### ISSUE TITLE
Unable to save polymorphic models to non-default databases

### ISSUE THREAD

**Issue by rp-austin** [chrisglass/django_polymorphic#216]
Saving subclasses of `PolymorphicModel` to databases other than `default` fails due to an error in the `PolymorphicModel.pre_save_polymorphic` method.

**Steps to reproduce:**

1. Configure the `example` Django project to use two databases. For example, change the `DATABASES` entry in `example/settings.py` to:
    ```python
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(PROJECT_ROOT, 'example.db'),
        },
        'secondary': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(PROJECT_ROOT, 'example2.db'),
        }
    }
    ```

2. Leave the `default` database empty. Migrate the project using the `secondary` database:

    ```bash
    python manage.py migrate --database secondary
    ```

3. Attempt to save an instance of a `PolymorphicModel` subclass using the `secondary` database:

    ```python
    from pexp.models import Model2A
    Model2A(field1='test').save(using='secondary')
    # or...
    Model2A.objects.db_manager('secondary').create(field1='test')
    ```

**Expected result:**

The instance is saved into the `secondary` database.

**Observed result:**

Saving fails with the following traceback:

```python
Traceback (most recent call last):
  File "/Users/austin/.virtualenvs/polymorphic/lib/python3.5/site-packages/django/core/management/commands/shell.py", line 69, in handle
    self.run_shell(shell=options['interface'])
  File "/Users/austin/.virtualenvs/polymorphic/lib/python3.5/site-packages/django/core/management/commands/shell.py", line 61, in run_shell
    raise ImportError
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/austin/.virtualenvs/polymorphic/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/austin/.virtualenvs/polymorphic/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: django_content_type

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/austin/.virtualenvs/polymorphic/lib/python3.5/site-packages/django/contrib/contenttypes/models.py", line 67, in get_for_model
    ct = self.get(app_label=opts.app_label, model=opts.model_name)
  File "/Users/austin/.virtualenvs/polymorphic/lib/python3.5/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/austin/.virtualenvs/polymorphic/lib/python3.5/site-packages/django/db/models/query.py", line 381, in get
    num = len(clone)
  File "/Users/austin/.virtualenvs/polymorphic/lib/python3.5/site-packages/django/db/models/query.py", line 240, in __len__
    self._fetch_all()
  File "/Users/austin/.virtualenvs/polymorphic/lib/python3.5/site-packages/django/db/models/query.py", line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/Users/austin/.virtualenvs/polymorphic/lib/python3.5/site-packages/django/db/models/query.py", line 52, in __iter__
    results = compiler.execute_sql()
  File "/Users/austin/.virtualenvs/polymorphic/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 848, in execute_sql
    cursor.execute(sql, params)
  File "/Users/austin/.virtualenvs/polymorphic/lib/python3.5/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/austin/.virtualenvs/polymorphic/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/austin/.virtualenvs/polymorphic/lib/python3.5/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/austin/.virtualenvs/polymorphic/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/austin/.virtualenvs/polymorphic/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/austin/.virtualenvs/polymorphic/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: django_content_type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/austin/Projects/django_polymorphic/polymorphic/models.py", line 91, in save
    self.pre_save_polymorphic(using=using)
  File "/Users/austin/Projects/django_polymorphic/polymorphic/models.py", line 84, in pre_save_polymorphic
    self.polymorphic_ctype = ContentType.objects.db_manager(using).get_for_model(self, for_concrete_model=False)
  File "/Users/austin/.virtualenvs/polymorphic/lib/python3.5/site-packages/django/contrib/contenttypes/models.py", line 80, in get_for_model
    "Error creating new content types. Please make sure contenttypes "
RuntimeError: Error creating new content types. Please make sure contenttypes is migrated before trying to migrate apps individually.
```

This particular issue is caused by the query to populate `polymorphic_ctype` in the `PolymorphicModel.pre_save_polymorphic` method. The general issue is that `ContentType` queries are always performed using the default object manager, and it's not possible to specify a database. That is, queries are always performed similar to this:

```python
ContentType.objects.get_for_model(self, for_concrete_model=False)
```

Instead of something like this:

```python
ContentType.objects.db_manager(using).get_for_model(self, for_concrete_model=False)
```

**Comment by rp-austin** [comment]
I forgot to link the pull request back to this. #217 closes this.
